package com.classityreal.iloadandroid.auth

// NOTE: `uniffi.isideload_android.AuthSession` / `LoginResult` / `LoginError`
// below don't exist as source in this repo — they're generated at build
// time by `rust/isideload-android`'s `uniffi-bindgen` binary from
// src/lib.rs, and CI (see .github/workflows/build.yml) drops the
// generated .kt file into this package before Gradle compiles the app.
// This file will not compile until that generation step has run once —
// see rust/isideload-android/src/lib.rs for the exact shape being bound.
//
// import uniffi.isideload_android.AuthSession
// import uniffi.isideload_android.LoginResult as FfiLoginResult
// import uniffi.isideload_android.LoginError as FfiLoginError

sealed class LoginOutcome {
    data class Success(val sessionBlob: ByteArray) : LoginOutcome()
    data object TwoFactorRequired : LoginOutcome()
    data class Failure(val message: String) : LoginOutcome()
}

/**
 * App-facing auth API. Holds one native AuthSession per login attempt;
 * the underlying object keeps the in-progress 2FA state, so this class
 * must not be recreated between `login()` and `submit2fa()` calls.
 */
class AuthBridge {

    // private val native = AuthSession()

    suspend fun login(appleId: String, password: String): LoginOutcome {
        // return try {
        //     when (val result = native.login(appleId, password)) {
        //         is FfiLoginResult.Success -> LoginOutcome.Success(result.session)
        //         is FfiLoginResult.TwoFactorRequired -> LoginOutcome.TwoFactorRequired
        //     }
        // } catch (e: FfiLoginError) {
        //     LoginOutcome.Failure(e.message ?: "login failed")
        // }
        TODO("Wire up once uniffi Kotlin bindings are generated by CI — see comment above")
    }

    suspend fun submit2fa(code: String): LoginOutcome {
        // return try {
        //     when (val result = native.submit2fa(code)) {
        //         is FfiLoginResult.Success -> LoginOutcome.Success(result.session)
        //         is FfiLoginResult.TwoFactorRequired -> LoginOutcome.TwoFactorRequired
        //     }
        // } catch (e: FfiLoginError) {
        //     LoginOutcome.Failure(e.message ?: "2FA code rejected")
        // }
        TODO("Wire up once uniffi Kotlin bindings are generated by CI — see comment above")
    }
}
